language: scala
scala:
  - 2.12.3
  - 2.11.11
jdk:
  - oraclejdk8

script: |
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: |
  sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
